name: falcor-pytorch
channels:
    - pytorch
    - nvidia
    - conda-forge
dependencies:
    - numpy
    - python=3.10
    - pytorch-cuda=11.8
    - torchaudio
    - torchvision
    - pip
    - pip:
        - pyexr
        - largesteps
        - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
        - matplotlib
        - tqdm
        - opencv-python
        - abc_property>=1.0
        - pandas
        - dictwrapper>=1.3
        - ruamel.yaml=0.16.12
